# Generated by Django 5.2.7 on 2025-11-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racas', to='petguard.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=100)),
                ('anos', models.PositiveIntegerField(default=0)),
                ('meses', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_tratamento', 'Em tratamento'), ('adotado', 'Adotado')], default='disponivel', max_length=30)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animais/')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petguard.especie')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petguard.raca')),
            ],
        ),
    ]
